# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
brews:
  -
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: co-pilot-cli
      name: homebrew-co-pilot

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://co-pilot-cli.github.io/"

    # Template of your app's description.
    # Default is empty.
    description: "Co-pilot is a developer tool for automating common tasks on a spring boot project."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"
